language: python
python:
- '2.7'

before_install:
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository -y ppa:saltstack/salt
  - sudo apt-get update
  - sudo apt-get install -y salt-master salt-minion

install:
  # Copy these states
  - sudo mkdir -p /srv/salt/states
  - sudo cp -r . /srv/salt/states
  - sudo cp .travis/minion /etc/salt/minion
  - sudo service salt-minion restart

  # Additional debug help
  - sudo cat /var/log/salt/*

  # See what kind of travis box you're on
  # to help with making your states compatible with travis
  - sudo salt-call grains.items --local

script:
  - sudo salt-call state.show_highstate --local --retcode-passthrough
